### ISSUE TITLE
Some endpoint returns a 404 response with a message not handled by the error handling

### ISSUE THREAD

**Issue by metaline** [metaline/activecampaign-sdk#1]
Some endpoint returns a 404 response with a message not handled by the error handling of this SDK. For example:

```php
$result = $client->put('contacts/18', $data);
$successful = $result->isSuccessful(); // false
$errors = $result->getErrors(); // empty array
```

But the internal response is like this:

```
HTTP/1.1 404 Not Found

{"message":"No Result found for Subscriber with id 18"}
```

We can improve the error handling and take the value of the `message` parameter (if it exists).

**Comment by omoikane** [comment]
Ok, the result of `$result->getErrors()` could become this:

```
[
    'errors' => [
        [
            'title' => 'No Result found for Subscriber with id 18',
        ],
    ],
]
```

I don't like the 'errors' level, but removing it we get a bc break...
